### ISSUE TITLE
How can I get the gas price paid in arbiscan

### ISSUE THREAD

**Issue by huahuayu** [OffchainLabs/go-ethereum#200]
Hi, there's a field named gas price paid in arbiscan, which is a new field created by you, in etherscan there's no such term.

Take this [tx](https://arbiscan.io/tx/0xda5d9797a16070e7360a81cada524d40691f721e448b4cb4041841346fc90be8) as an example:  
![image](https://user-images.githubusercontent.com/1725060/219573258-cbca2ef4-098e-44d1-98bd-e7dd018c294c.png)

I can't get the field in anywhere,  neither in `types.Transaction` nor `types.Receipt`.

May I know where I can get it?

**Comment by gzeoneth** [comment]
It's the effectiveGasPrice in receipt.
