### ISSUE TITLE
Upgrade go-ethereum code to compatibility with EigenDA

### ISSUE THREAD

**Issue by prpeh** [OffchainLabs/go-ethereum#323]
# Rationale

To integrate Artribum L2 Orbit with EigenDA. 

The issue is [EigenDA](https://github.com/Layr-Labs/eigenda/blob/dbbe9d1df5741e7cc32d833df7b07a3ebc733ea7/go.mod#L14C2-L14C41) now require `ethereum/go-ethereum` v1.14.0 that use[ pebble v1.1.0](https://github.com/Layr-Labs/eigenda/blob/dbbe9d1df5741e7cc32d833df7b07a3ebc733ea7/go.mod#L71C32-L71C37) but currently nitro node use OffchainLabs/go-ethereum with very old version of pebble v0.0.0-20230928194634-aa077af62593. That will make version conflict of pebble when making integration nitro node with EigenDA.

# Implementation

- Rebase this repo with ethereum/go-ethereum v1.14.0  to compatibility with EigenDA

**Comment by cryptix** [comment]
I don't see a PR linked and the dependency tree still looks like 1.13, so I'm assuming this hasn't actually happened?
