### ISSUE TITLE
Update readme with fork rationale

### ISSUE THREAD

**Issue by cryptix** [OffchainLabs/go-ethereum#334]
Hi,

Thanks a lot for this! I found this repo via the `transaction type not supported` issue on upstream.

As far as I can tell the main reason for the fork is/was L2 support but which networks exactly are in/out of scope and whether this fork also still works to interact with L1 is really hard to tell from the outside since the README is still the upstream one, I believe? 

Maybe this information is somewhere else. I haven't been able to find it if so.

**Comment by bbenzikry** [comment]
We tried the latest passing master and it didn't seem to work well on L2s we work with.
We ended up using our up to date geth fork and just handled opstack and others ourselves ( mostly for ethclient use though )
